package com.sidorykp.sandbox.vaadin.jpacontainer.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;

public class VisuallyDesignedReusable extends CustomComponent
{

    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private Button button_2;
    @AutoGenerated
    private Button button_1;

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public VisuallyDesignedReusable()
    {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout()
    {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // button_1
        button_1 = new Button();
        button_1.setCaption("Save Changes");
        button_1.setImmediate(true);
        button_1.setWidth("-1px");
        button_1.setHeight("-1px");
        mainLayout.addComponent(button_1, "top:14.0px;left:20.0px;");
        
        // button_2
        button_2 = new Button();
        button_2.setCaption("Cancel");
        button_2.setImmediate(true);
        button_2.setWidth("-1px");
        button_2.setHeight("-1px");
        mainLayout.addComponent(button_2, "top:14.0px;left:160.0px;");
        
        return mainLayout;
    }

}
