package com.sidorykp.sandbox.vaadin.jpacontainer.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.RichTextArea;

public class VisuallyDesigned extends CustomComponent {

	@AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private VisuallyDesignedReusable visuallyDesignedReusable_1;
    @AutoGenerated
    private RichTextArea richTextArea_1;

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VisuallyDesigned() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
    private AbsoluteLayout buildMainLayout()
    {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // richTextArea_1
        richTextArea_1 = new RichTextArea();
        richTextArea_1.setImmediate(false);
        richTextArea_1.setWidth("-1px");
        richTextArea_1.setHeight("-1px");
        mainLayout.addComponent(richTextArea_1, "top:20.0px;left:20.0px;");
        
        // visuallyDesignedReusable_1
        visuallyDesignedReusable_1 = new VisuallyDesignedReusable();
        visuallyDesignedReusable_1.setImmediate(false);
        visuallyDesignedReusable_1.setWidth("500px");
        visuallyDesignedReusable_1.setHeight("80px");
        mainLayout.addComponent(visuallyDesignedReusable_1,
                "top:240.0px;left:20.0px;");
        
        return mainLayout;
    }

}
